# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BHL413ACx65Z0ZdDeQj5DxySurPwFlYQ

**Convolutional Neural Networks**

Part 1 - Building the CNN
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x

#from google.colab import drive
#drive.mount('/content/gdrive')

#importing the keras libraries and packages
from keras.models import Sequential
from keras.layers import Convolution2D, MaxPooling2D, Flatten, Dense

#initialising the CNN
classifier = Sequential()

#Step 1 - Convolution
classifier.add(Convolution2D(32,(3,3),input_shape=(64,64,3),activation='relu'))
#classifier.add(Convolution2D(32,3,3,input_shape=(64,64,3),activation='relu'))

#Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size=(2,2)))

#adding a second convolutional layer
classifier.add(Convolution2D(32,(3,3),activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2,2)))

#Step 3 - Flattening
classifier.add(Flatten())

#Step 4 - Connection
classifier.add(Dense(units=128,activation="relu"))
#classifier.add(Dense(output_dim=6,activation="relu"))
classifier.add(Dense(units=1,activation="sigmoid"))
#classifier.add(Dense(output_dim=1,activation="sigmoid"))

#compiling the CNN
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

"""Part 2 - Fitting the CNN to the images"""

from keras.preprocessing.image import ImageDataGenerator
 train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory('/content/gdrive/My Drive/Colab/dataset/training_set',
                                                 target_size=(64, 64),
                                                 batch_size=32,
                                                 class_mode='binary')

test_set = test_datagen.flow_from_directory('/content/gdrive/My Drive/Colab/dataset/test_set',
                                            target_size=(64, 64),
                                            batch_size=32,
                                            class_mode='binary')

classifier.fit_generator(training_set,
                    steps_per_epoch=8000,                   #samples_per_epoch=8000
                    epochs=25,                              #nb_epochs=25
                    validation_data=test_set,
                    validation_steps=2000)                  #nv_val_samples